#!/usr/bin/env python3 
import sys
import os
from PIL import Image

def setingrid(width, height, valuelist):
    arr = []
    for row in valuelist[0:len(valuelist):width]:
        current_row = []
        for col in range(width):
            current_row.append(valuelist[valuelist.index(row)+col])
        arr.append(current_row)
    print(arr)


arguments = [x for x in sys.argv[1:]]

def main():
    for file in arguments:
        with Image.open(file,'r') as im:
            pix_val = list(im.getdata())
            col_val = []
            for pixel in pix_val:
                if pixel[0]>pixel[1] and pixel[0]>pixel[2]:
                    col_val.append('R')
                elif pixel[1]>pixel[0] and pixel[1]>pixel[2]:
                    col_val.append('G')
                elif pixel[2]>pixel[0] and pixel[2]>pixel[1]:
                    col_val.append('B')
                else:
                    col_val.append('_')
                    

            width,height = im.size
            setingrid(width,height,pix_val)
            setingrid(width,height,col_val)
            
if __name__ == "__main__":
    main()


